/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author mathe
 */
public class Inicio_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_GUI
     */
    public Inicio_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel1 = new org.edisoncor.gui.panel.Panel();
        jLabel1 = new javax.swing.JLabel();
        close_system = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        preferentialKey = new org.edisoncor.gui.button.ButtonAction();
        reload = new org.edisoncor.gui.button.ButtonAction();
        print_key = new org.edisoncor.gui.button.ButtonAction();
        commonKey = new org.edisoncor.gui.button.ButtonAction();
        jScrollPane1 = new javax.swing.JScrollPane();
        common_key_txt = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        preferential_key_txt = new javax.swing.JTextArea();
        jDayChooser1 = new com.toedter.calendar.JDayChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setColorPrimario(new java.awt.Color(51, 0, 255));
        panel1.setColorSecundario(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pegue a sua senha e aguarde ser chamado...");

        close_system.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        close_system.setText("Fechar");
        close_system.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_systemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(close_system)
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(close_system, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Senha comum");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, 154, 27));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Senha Preferencial");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 72, 164, 27));

        preferentialKey.setText("Senha Preferencial");
        preferentialKey.setColorDeSombra(new java.awt.Color(102, 102, 255));
        preferentialKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferentialKeyActionPerformed(evt);
            }
        });
        jPanel1.add(preferentialKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 276, 180, -1));

        reload.setText("Reiniciar");
        reload.setColorDeSombra(new java.awt.Color(102, 102, 255));
        reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadActionPerformed(evt);
            }
        });
        jPanel1.add(reload, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 322, 180, -1));

        print_key.setText("Imprimir senha");
        print_key.setColorDeSombra(new java.awt.Color(102, 102, 255));
        print_key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_keyActionPerformed(evt);
            }
        });
        jPanel1.add(print_key, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 368, 180, -1));

        commonKey.setText(" Senha comum");
        commonKey.setColorDeSombra(new java.awt.Color(102, 102, 255));
        commonKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonKeyActionPerformed(evt);
            }
        });
        jPanel1.add(commonKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 230, 180, -1));

        common_key_txt.setColumns(20);
        common_key_txt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        common_key_txt.setLineWrap(true);
        common_key_txt.setRows(5);
        common_key_txt.setWrapStyleWord(true);
        jScrollPane1.setViewportView(common_key_txt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 121, 154, 282));

        preferential_key_txt.setColumns(20);
        preferential_key_txt.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        preferential_key_txt.setLineWrap(true);
        preferential_key_txt.setRows(5);
        preferential_key_txt.setWrapStyleWord(true);
        jScrollPane2.setViewportView(preferential_key_txt);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 121, 165, 282));
        jPanel1.add(jDayChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(600, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void close_systemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_systemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_close_systemActionPerformed

    private void commonKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commonKeyActionPerformed
        Controller.Gerar_senha_DAO.SenhaComum();
    }//GEN-LAST:event_commonKeyActionPerformed

    private void preferentialKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preferentialKeyActionPerformed
        Controller.Gerar_senha_DAO.SenhaPreferencial();
    }//GEN-LAST:event_preferentialKeyActionPerformed

    private void reloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadActionPerformed
        Controller.Reiniciar_DAO.Reload();
    }//GEN-LAST:event_reloadActionPerformed

    private void print_keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_keyActionPerformed
        Controller.Imprimir_DAO.ImprimirSenha();
    }//GEN-LAST:event_print_keyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close_system;
    private org.edisoncor.gui.button.ButtonAction commonKey;
    public static javax.swing.JTextArea common_key_txt;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.button.ButtonAction preferentialKey;
    public static javax.swing.JTextArea preferential_key_txt;
    private org.edisoncor.gui.button.ButtonAction print_key;
    private org.edisoncor.gui.button.ButtonAction reload;
    // End of variables declaration//GEN-END:variables
}
